name: Terraform ServiceCatalog Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # <-- Add init with upgrade here
      - name: Terraform Init
        run: terraform -chdir=servicecatalog init -upgrade

      - name: Terraform Plan
        run: terraform -chdir=servicecatalog plan

      - name: Terraform Apply
        run: terraform -chdir=servicecatalog apply -auto-approve
